/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Fri Oct 21 14:57:31 2016. */

#include "sems.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sems_SensorData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sems_SensorData, type, type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, sems_SensorData, data, type, 0),
    PB_LAST_FIELD
};

const pb_field_t sems_SensorDataList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, sems_SensorDataList, list, list, &sems_SensorData_fields),
    PB_LAST_FIELD
};

const pb_field_t sems_ActionData_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sems_ActionData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, sems_ActionData, cmd, id, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, sems_ActionData, data, cmd, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, sems_ActionData, state, data, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(sems_SensorDataList, list) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_sems_SensorData_sems_SensorDataList_sems_ActionData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(sems_SensorDataList, list) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_sems_SensorData_sems_SensorDataList_sems_ActionData)
#endif


/* @@protoc_insertion_point(eof) */
